const langButton = document.querySelector('.lang');
const descriptions = document.querySelectorAll('.discrption');

let currentLanguage = 'en'; // Initial language

const translations = {
  en: {
    // Translations for each description element ID or class
    d1: "A traditional village inhabited by the Dorze people, located in the mountains near Arba Minch. A bustling town with a population of around 100,000 people.Known as the Gateway to the Omo Valley due to its proximity to this culturally diverse region.",
    d2: " Lake Chamo is a lake in the Southern Nations, Nationalities, and Peoples' Region of southern Ethiopia. Located in the Main Ethiopian Rift, it is at an elevation of 1,110 meters. The Chamo lake is just to the south of Lake Abaya and the city of Arba Minch, east of the Guge Mountains, and west of the Amaro Mountains.",
    d3: " The Gamo people are an Ethiopian ethnic group located in the Gamo Highlands of southern Ethiopia. They are found in more than 40 communities, including Chencha, Bonke, Kucha, Garbansa, Zargula, Kamba, Dorze, Birbir, Ochello, Boroda, Ganta, Gacho Baba, Eligo, Shella, Kolle, Dita, Kogo and Daramalo",
    d4:"Towering whispers meet playful swings, laughter's echo through Forty Springs. Sunlight paints leaves in vibrant hues, where monkeys feast and joy imbues. Hidden springs, an unseen hand, nourish gardens lush and grand. Dive in, cool emerald embrace, count springs that vanish in time's space. Smile, dear guest, for magic lingers, a timeless friend with verdant fingers.",
    d5:" Nechisar National Park is in southwest Ethiopia. Its varied terrain spans escarpments, swamps and forest. Zebras and gazelles roam the vast savannahs of the Nechisar Plains. The large, brown-red Lake Abaya sits on the north side of the mountainous Bridge of God isthmus. To the south is Lake Chamo, known for its big Nile crocodiles. The park is home to many birds, including the rare Nechisar nightjar.",
    d6:" The Omo valley is dominated mainly by many ethnic groups who speak Omotic language as classified by linguistics. The region and the people are one of the least affected by the modern world. The life style of the people has hardly changed for centuries. People still live in simple make shift huts, dress animal skins and drink from calabashes. The area is a veritable paradise for photographers and naturalists.",
    j1:"Abba Jifar II was king of Jimma,[1] and the son of Abba Gomol and Queen Gumiti. He had several wives: Queen Limmiti, who was the daughter of the King of Limmu-Ennarea; Queen Minjo, the daughter of the King of Kaffa; and Queen Sapertiti, also from Limmu-Ennarea.",
    j2:"Bonga is a town, woreda and one of the multicapital of the South West Ethiopia Peoples' Region in Ethiopia. Located in the Keffa Zone upon a hill in the upper Barta valley, it has a latitude and longitude of 7°16′N 36°14′E with an elevation of 1,714 meters above sea level. Not confused with another town named Bonga, near Gambela Region",
    j3:"Ethiopia is building a new lodge called Denbi Lake Lodge as part of a bigger plan to develop 8 new tourism destinations. This project is expected to boost the economy and highlight the natural beauty of the Bench Sheko Zone. Construction will take about 1.5 years and is expected to be completed by Midroc Ethiopia. It's one of many efforts to make Ethiopia a more attractive tourist destination.",
    j4:"An early morning trek after breakfast will take you to Mankira, the place where coffee Arabica was discovered. En route visit the ancient Adaracha Medhane Alem church and the Gurguto natural Bridge. You will have dinner and spend the night at the hotel. Overnight stay in Kaffa Guest house",
    j5:"This naturally processed coffee is selectively harvested and hand sorted at the Wush Wush washing station in Ethiopia's Keffa Zone. Producing natural coffee is relatively new to this washing station. Due to the wet weather, using this method requires careful monitoring and tight process control. The results of their rigorous labor is in the cup.",
    j6:"Jimma Industrial Park (75 hectares) is located in Jimma. It is 352 km from Addis Ababa. It has started operations at end of 2019, with 9 factory sheds already rented out to one Chinese company. It specializes in Apparel & Garment and 100% exportable products. It has access to a domestic airport.",
    w1:"  Amba Geshen is the name of a mountain in northern Ethiopia. It is in Ambassel, South Wollo Zone of the Amhara Region, northwest of Dessie, at a latitude and a longitude of 11°31′N 39°21′E. Part of Ambassel woreda, Amba Geshen is one of the mountains of Ethiopia where most of the male heirs to the Emperor of Ethiopia were interned, usually for life. Also known as Gishen Mariam, it was the second of the three such mountains, or amba, said to have been used for this purpose, the other two being Debre Damo and Wehni.",
    w2:"Lalibela (Amharic: ላሊበላ) is a town in the Amhara Region of Ethiopia. Located in the Lasta district and North Wollo Zone, it is a tourist site for its famous rock-cut monolithic churches. The whole of Lalibela is a large and important site for the antiquity, medieval, and post-medieval civilization of Ethiopia.[1] To Christians, Lalibela is one of Ethiopia's holiest cities, and a center of pilgrimage.",
    a1:"Afar people have traditionally practiced Islam. They also believe in the spirits of ancestors which is evident by a yearly feast called Rabena which means “feast of the dead.” The Afar people live in small shelters that can be easily disassembled and reassembled to fi t their nomadic pastoralist lifestyles.",
    a2:"The Danakil Depression is the northern part of the Afar Triangle or Afar Depression in Ethiopia and Eritrea,[1][2] a geological depression that has resulted from the divergence of three tectonic plates in the Horn of Africa. It is the third lowest lying location on the continent of Africa.",
    a3:"Why is Dinknesh famous? Dinknesh probably lived 3.2 million years ago. When her fossilized bones were excavated in 1974, she was hailed as the oldest early human — or hominin — ever found. Scientists also found 40 percent of her bones, making her the most complete skeleton of an early human species. Dinknesh belonged to a new species, which was given the scientific name Australopithecus afarensis ('southern ape from afar' in Latin). ",
    a4:"Erta Ale is a continuously active basaltic shield volcano in the Afar Region of northeastern Ethiopia, which is itself part of the wider Afar Triangle. The volcano is located in the Danakil Depression, an area on the border between Ethiopia and Eritrea that is below sea level.",
    a5:"Lake Asale is a huge salt pan in the Danakil Depression. It is 115 meters below sea level. This is the ‘salt kingdom’ of the Afar, where they daily grind salt into tablets. These people have been doing this for centuries in an area of approximately 1200 kilometers.",
    g1:" 1.	Eskista (Shoulder Dance): Eskista hails from the historic city of Gondar and is native to the Amhara region. Performed by both men and women, usually in groups. Known for its intricate shoulder movements, which are said to be inspired by the sinuous motions of a snake.Dancers create mesmerizing patterns with their shoulders, arms, and upper body.Eskista is an expression of joy, celebration, and community bonding during festivals, weddings, and other special occasions.",
    g2:"Gonder Castle, also known as the Fasil Ghebbi, is a remarkable fortress located in Gondar, Amhara Region, Ethiopia.Fasil Ghebbi (Royal Enclosure):Founded by Emperor Fasilides, in the 17th century.The complex served as a hub for political, cultural, and administrative activities.The architecture of Fasil Ghebbi reflects a blend of diverse influences:",
    g3:"Simien Mountains National Park is the largest national park in Ethiopia. It lies in the North Gondar Zone of the Amhara Region. The park covers the highest parts of the Simien Mountains, including Ras Dashan, Ethiopia’s highest peak. it i Home to several endangered species, including:  Ethiopian wolf,	Walia ibex,	Gelada baboon,Caracal and etc.",
    g4:" Sekela Abay is a captivating travel show that embarks on a remarkable journey along the world’s longest river, the Abay (Nile). The show follows the Nile (Abay) for 365 days non-stop. Starting from the source of the Nile in Sekela, the adventure unfolds. it is rich cultural heritage, landscapes, and people along the Nile’s course. From the serene beginnings to the powerful flow downstream, every moment is captured.",
    g5:"Tanna is an island in the Tafea Province of Vanuatu in the southwestern Pacific Ocean. It is 25 miles long and 12 miles wide, with a total area of 212 square miles.The name Tanna is derived from the word tana in the Kwamera language, meaning earth. Tanna is volcanic in origin and has a tropical climate, making it the most fertile island in Vanuatu. It produces copra, coffee, and cattle for export. The island is home to Mount Tukosmera, which is its highest point at 1,084 meters.",
    t1:"The Aksumite Civilization in the ancient city of Aksum, located in modern-day Ethiopia, is known for its impressive monuments, particularly the monolithic obelisks.These obelisks, dating from the 3rd and 4th centuries AD, are unique masterpieces of human creativity Carved mainly from solid blocks of nepheline syenite,these obelisks are believed to have come from quarries several miles west of Aksum. The tallest stelae likely commemorated royalty, while smaller ones were probably commissioned by local elites.",
    t2:" Aksum Tsion, also known as Maryam Tsion, is a sacred site within the Ethiopian OrthodoxTewahido Church, located in the Tigray region of Northern Ethiopia. This church is considered one of the oldest in Ethiopia, tracing back to the time of Christianity's introduction in the country. Emperor Fasiledes rebuilt the church after it was destroyed by Ahmad ibn Ibrahim al-Ghazi in the 16th century, and Emperor Haile Selassie constructed the elaborate current church structure in the 1950s. ",
    t3:" The Al Nejashi Mosque is located in Negash, Tigray, Ethiopia. It is believed to be Africa's first mosque, established after 615 CE when the first Muslims migrated to Abyssinia during the reign of Najashi, after fleeing persecution in Mecca.The mosque was named after Najashi and has historical significance as a place of refuge for early Muslims. In 2018, the mosque underwent renovation with funding from the Turkish Cooperation and Coordination Agency.",
    t4:"Debre Damo is a monastery located on an isolated mountain in the northern part of Tigray,  Ethiopia. It was built in the sixth century AD and is unique compared to most Ethiopian monasteries. Debre Damo is only accessible by climbing up by a rope, which is made of plaited leather, lowered from the cliffs, which visitors tie around their waist and are then pulled up by a monk at the top of the cliffs. It is only accessible to men and male animals. ",
    t5:" Abuna Yemata Guh is a monolithic church located in the Hawzen woreda of the Tigray Region, Ethiopia. Situated at a height of 2,580 meters (8,460 feet), this church is known for its challenging yet rewarding climb and its historical significance. Carved into the side of a tall sandstone spire in the Gheralta area, the church dates back to the 5th century and is dedicated to Abuna Yemata, one of the Nine Saints who played a crucial role in spreading Christianity in Ethiopia."


  },
  amh: {
    // Translations for each description element ID or class
    d1: "በአርባ ምንጭ አቅራቢያ በሚገኙ ተራሮች ላይ የምትገኝ የዶርዜ ሰዎች የሚኖሩባት ባህላዊ መንደር። ወደ 100,000 ህዝብ የሚኖርባት ብዙ የሚበዛባት ከተማ።ለዚህ የባህል ስብጥር ክልል ካለው ቅርበት የተነሳ የኦሞ ሸለቆ መግቢያ በመባል ይታወቃል።",
    d2: "የጫሞ ሀይቅ በደቡብ ኢትዮጵያ ደቡብ ብሄር ብሄረሰቦችና ህዝቦች ክልል የሚገኝ ሀይቅ ነው። በዋናው የኢትዮጵያ ስምጥ ውስጥ የሚገኘው በ1,110 ሜትር ከፍታ ላይ ነው። የጫሞ ሀይቅ ከአባያ ሀይቅ በስተደቡብ እና አርባ ምንጭ ከተማ ከጉጌ ተራራ በምስራቅ እና ከአማሮ ተራሮች በስተ ምዕራብ ይገኛል።",
    d3: "የጋሞ ብሄረሰብ በደቡብ ኢትዮጵያ በጋሞ ሀይላንድ የሚገኝ የኢትዮጵያ ብሄረሰብ ነው። በቼንቻ፣ ቦንኬ፣ ኩቻ፣ ጋርርባንሳ፣ ዛርጉላ፣ ካምባ፣ ዶርዜ፣ ቢርቢር፣ ኦቼሎ፣ ቦሮዳ፣ ጋንታ፣ ጋቾ ባባ፣ ኤሊጎ፣ ሼላ፣ ኮሌ፣ ዲታ፣ ኮጎ እና ዳራማሎ ጨምሮ ከ40 በላይ ማህበረሰቦች ይገኛሉ።",
    d4:"ከፍ ያሉ ሹክሹክታዎች ተጫዋች ዥዋዥዌን ይገናኛሉ፣ የሳቅ ድምፅ በአርባ ምንጭ በኩል ያስተጋባል። የፀሐይ ብርሃን ዝንጀሮዎች የሚበሉበት እና የደስታ ስሜት በሚታይባቸው ደማቅ ቀለሞች ቅጠሎችን ይሳሉ። የተደበቁ ምንጮች፣ የማይታይ እጅ፣ ለምለም እና ታላቅ የአትክልት ስፍራዎችን ይመገባሉ። ዘልለው ይግቡ፣ አሪፍ ኤመራልድ እቅፍ አድርገው፣ በጊዜ ክፍተት የሚጠፉ ምንጮችን ይቆጥሩ። ፈገግ ይበሉ ፣ ውድ እንግዳ ፣ ለአስማት ዘግይቷል ፣ ጊዜ የማይሽረው ጣቶች ያሉት ጓደኛ።",
    d5:"የኔቺሳር ብሔራዊ ፓርክ በደቡብ ምዕራብ ኢትዮጵያ ይገኛል። የተለያየ መልክዓ ምድሯ የተንጣለለ, ረግረጋማ እና ጫካን ያካትታል. የሜዳ አህያ እና የሜዳ ዝርያዎች በኔቺሳር ሜዳ ውስጥ በሚገኙ ሰፊ ሳቫናዎች ይንከራተታሉ። ትልቁ፣ ቡናማ-ቀይ የአባያ ሀይቅ ከተራራማው የእግዚአብሔር ድልድይ በስተሰሜን በኩል ተቀምጧል። በደቡብ በኩል በትልልቅ የአባይ አዞዎች የሚታወቀው የጫሞ ሀይቅ አለ። ፓርኩ ብርቅየውን የኔቺሳር ናይትጃርን ጨምሮ የበርካታ ወፎች መኖሪያ ነው።",
    d6:"የኦሞ ሸለቆ በዋነኛነት በብዙ ብሔረሰቦች ቁጥጥር ስር ያለ ሲሆን የኦሞቲክ ቋንቋ በሚናገሩ በቋንቋ ሊቃውንት ይመደባሉ። ክልሉ እና ህዝቡ በዘመናዊው ዓለም ከተጎዱት መካከል አንዱ ነው. የህዝቡ የአኗኗር ዘይቤ ለዘመናት ብዙም አልተለወጠም። ሰዎች አሁንም የሚኖሩት በቀላል የፈረቃ ጎጆዎች፣ የእንስሳት ቆዳ ለብሰው እና ከካላባሽ ይጠጣሉ። አካባቢው ለፎቶግራፍ አንሺዎች እና የተፈጥሮ ተመራማሪዎች እውነተኛ ገነት ነው።",
    j1:"አባ ጅፋር 2ኛ የጅማ ንጉሥ ነበር [1] እና የአባ ጎሞል እና የንግሥት ጉሚቲ ልጅ። እሱ ብዙ ሚስቶች ነበሩት: የሊሙ-ኤንናሪያ ንጉስ ሴት ልጅ የሆነችው ንግስት ሊሚቲ; የካፋ ንጉስ ሴት ልጅ ንግሥት ሚንጆ; እና ንግስት ሳፐርቲቲ፣ እንዲሁም ከሊሙ-ኤንናሬአ።",
    j2:"ቦንጋ ከተማ፣ ወረዳ እና በደቡብ ምእራብ ኢትዮጵያ ህዝቦች ክልል ውስጥ በኢትዮጵያ ከሚገኙት ሁለገብ ዋና ከተማዎች አንዱ ነው። በከፋ ዞን በላይኛው ባርታ ሸለቆ ላይ በሚገኝ ኮረብታ ላይ የሚገኘው 7°16′N 36°14′E ኬክሮስ እና ኬንትሮስ ከባህር ጠለል በላይ 1,714 ሜትር ከፍታ አለው። በጋምቤላ ክልል አቅራቢያ ቦንጋ ከሚባል ከተማ ጋር አልተምታታም።",
    j3:"ኢትዮጵያ 8 አዳዲስ የቱሪዝም መዳረሻዎችን ለማልማት በያዘችው ትልቅ እቅድ መሰረት ደንቢ ሀይቅ ሎጅ የተባለ አዲስ ሎጅ በመገንባት ላይ ትገኛለች። ይህ ፕሮጀክት ኢኮኖሚውን እንደሚያሳድግ እና የቤንች ሸኮ ዞን የተፈጥሮ ውበትን እንደሚያጎላ ይጠበቃል። ግንባታው 1.5 ዓመታት የሚፈጅ ሲሆን በሜድሮክ ኢትዮጵያ ይጠናቀቃል ተብሎ ይጠበቃል። ኢትዮጵያን ይበልጥ ማራኪ የቱሪስት መዳረሻ ለማድረግ ከብዙ ጥረቶች አንዱ ነው።",
    j4:"ከቁርስ በኋላ በማለዳ የእግር ጉዞ ወደ ማንኪራ ይወስደዎታል, ቡና አረቢካ የተገኘበት ቦታ. በመንገድ ላይ ጥንታዊውን አደራቻ መድኃኔዓለም ቤተ ክርስቲያን እና የጉርጉቶ የተፈጥሮ ድልድይ ይጎብኙ። እራት በልተህ በሆቴሉ ታድራለህ። በካፋ የእንግዳ ማረፊያ አዳር",
    j5:"ይህ በተፈጥሮ የተቀነባበረ ቡና በኢትዮጵያ ከፋ ዞን ዉሽ ዉሽ ማጠቢያ ጣቢያ ተመርጦ በእጅ ይከፋፈላል። ለዚህ ማጠቢያ ጣቢያ የተፈጥሮ ቡና ማምረት በአንፃራዊነት አዲስ ነው። በእርጥብ የአየር ሁኔታ ምክንያት, ይህንን ዘዴ በመጠቀም ጥንቃቄ የተሞላበት ክትትል እና የሂደቱን ጥብቅ ቁጥጥር ይጠይቃል. የጠንካራ ጉልበታቸው ውጤት በጽዋው ውስጥ ነው.",
    j6:"የጅማ ኢንዱስትሪያል ፓርክ (75 ሄክታር) በጅማ ይገኛል። ከአዲስ አበባ 352 ኪ.ሜ. እ.ኤ.አ. በ2019 መጨረሻ ላይ ሥራ ጀምሯል ፣ 9 የፋብሪካ ሼዶች ቀድሞውኑ ለአንድ የቻይና ኩባንያ ተከራይተዋል። በአልባሳት እና አልባሳት እና 100% ወደ ውጭ የሚላኩ ምርቶች ላይ ያተኮረ ነው። የአገር ውስጥ አየር ማረፊያ መዳረሻ አለው.",
    w1:"አምባ ግሸን በሰሜን ኢትዮጵያ የሚገኝ ተራራ ስም ነው። በአማራ ክልል ደቡብ ወሎ ዞን አምባሰል ከደሴ ሰሜን ምዕራብ አቅጣጫ 11°31′N 39°21′E ኬክሮስ እና ኬንትሮስ ላይ ይገኛል። የአምባሰል ወረዳ ከፊል አምባ ግሸን የኢትዮጵያ ንጉሠ ነገሥት ወራሾች በአብዛኛው እድሜ ልክ ከታሰሩባቸው የኢትዮጵያ ተራራዎች አንዱ ነው። ግሸን ማርያም ተብሎም የሚጠራው ለዚህ ዓላማ ጥቅም ላይ ውለዋል ከተባሉት ከሦስቱ ተራራዎች መካከል ሁለተኛው ወይም አምባ ሲሆን የተቀሩት ሁለቱ ደብረ ዳሞ እና ወህኒ ናቸው።",
    w2:"ላሊበላ በኢትዮጵያ የአማራ ክልል ከተማ ነው። በላስታ አውራጃ እና በሰሜን ወሎ ዞን ውስጥ የሚገኝ ሲሆን ታዋቂው ውቅር አብያተ ክርስቲያናት የቱሪስት ቦታ ነው። መላው የላሊበላ የኢትዮጵያ ጥንታዊነት፣ የመካከለኛው ዘመን እና የድህረ-መካከለኛው ዘመን ስልጣኔ ትልቅ እና ጠቃሚ ቦታ ነው።[1] ለክርስቲያኖች ላሊበላ ከኢትዮጵያ ቅድስተ ቅዱሳን ከተሞች አንዷ እና የጉዞ ማዕከል ናት።",
    a1:"የአፋር ህዝብ እስልምናን በባህላዊ መንገድ ኖሯል። በተጨማሪም ራቤና ተብሎ በሚጠራው ዓመታዊ በዓል ትርጉሙም “የሙታን በዓል” ተብሎ በሚጠራው የአባቶች መንፈስ በሚታየው የአባቶች መንፈስ ያምናሉ። የአፋር ህዝብ ከአርብቶ አደር አኗኗሩ ጋር በሚስማማ መልኩ በቀላሉ ተነጣጥለው ሊገጣጠሙ በሚችሉ ትንንሽ መጠለያዎች ውስጥ ይኖራሉ።",
    a2:"የደናኪል ዲፕሬሽን የአፋር ትሪያንግል ሰሜናዊ ክፍል ወይም የአፋር ዲፕሬሽን በኢትዮጵያ እና ኤርትራ [1] [2] በአፍሪካ ቀንድ ውስጥ ባሉ የሶስት ቴክቶኒክ ፕሌቶች ልዩነት የተነሳ የጂኦሎጂካል ድብርት ነው። በአፍሪካ አህጉር ላይ ሦስተኛው ዝቅተኛው የውሸት ቦታ ነው።",
    a3:"ድንቅነሽ ለምን ታዋቂ ሆነ? ድንቅነሽ ከ3.2 ሚሊዮን ዓመታት በፊት ኖራለች። እ.ኤ.አ. በ 1974 ቅሪተ አካል አጥንቶቿ በቁፋሮ ሲወጡ፣ እስካሁን ድረስ ከተገኙት ሁሉ እጅግ ጥንታዊት የሰው ልጅ - ወይም ሆሚኒን ተብላ ተወደሰች። ሳይንቲስቶችም 40 በመቶ የሚሆነውን አጥንቶቿን በማግኘታቸው ከመጀመሪያዎቹ የሰው ዘር ዝርያዎች በጣም የተሟላ አፅም አድርጓታል። ድንቅነሽ የአዲሱ ዝርያ አባል ነበረች፣ እሱም ሳይንሳዊ ስም አውስትራሎፒተከስ አፋረንሲስ ",
    a4:"ኤርታ አሌ በሰሜን ምስራቅ ኢትዮጵያ በአፋር ክልል ውስጥ ያለማቋረጥ የሚንቀሳቀስ ባሳልቲክ ጋሻ እሳተ ገሞራ ነው፣ እሱም ራሱ የሰፊው የአፋር ትሪያንግል አካል ነው። እሳተ ገሞራው የሚገኘው በደናኪል ዲፕሬሽን፣ በኢትዮጵያ እና በኤርትራ አዋሳኝ አካባቢ ከባህር ወለል በታች ነው።",
    a5:"አሳሌ ሀይቅ በደናኪል ዲፕሬሽን ውስጥ ትልቅ የጨው መጥበሻ ነው። ከባህር ጠለል በታች 115 ሜትር ነው. ይህ የአፋር ‘የጨው መንግሥት’ ሲሆን በየቀኑ ጨው ወደ ጽላት የሚፈጩበት። እነዚህ ሰዎች ይህን ለዘመናት ሲያደርጉት የነበረው በግምት 1200 ኪሎ ሜትር አካባቢ ነው።",
    g1:"1. እስክስታ (የትከሻ ዳንስ) እስክስታ ከታሪካዊቷ ጎንደር ከተማ የመጣ ሲሆን የአማራ ክልል ተወላጅ ነው።በወንዶችም በሴቶችም በተለምዶ በቡድን ይከናወናል።በእባቡ የኃጢያት እንቅስቃሴዎች ተመስጧዊ ናቸው በሚባሉት ውስብስብ የትከሻ እንቅስቃሴዎች ይታወቃል።ዳንሰኞች በትከሻቸው፣ ክንዳቸው እና በላይኛው ሰውነታቸው አስመሳይ ንድፎችን ይፈጥራሉ።እስክስታ በበዓላት፣ በሠርግ እና በሌሎች ልዩ አጋጣሚዎች የደስታ፣ የአከባበር እና የማህበረሰብ ትስስር መግለጫ ነው።",
    g2:"የጎንደር ግንብ፣ እንዲሁም ፋሲል ግብቢ በመባል የሚታወቀው፣ በጎንደር፣ በአማራ ክልል፣ ኢትዮጵያ ውስጥ የሚገኝ አስደናቂ ምሽግ ነው። , እና አስተዳደራዊ ተግባራት. የፋሲል ገብቢ አርክቴክቸር የተለያየ ተጽእኖዎችን ያንፀባርቃል፡-",
    g3:"ስምየን ተራሮች ብሄራዊ ፓርክ በኢትዮጵያ ውስጥ ትልቁ ብሄራዊ ፓርክ ነው። በአማራ ክልል ሰሜን ጎንደር ዞን ይገኛል። ፓርኩ የኢትዮጵያ ከፍተኛ ጫፍ የሆነውን ራስ ዳሽንን ጨምሮ ከፍተኛውን የሲሚን ተራሮች ይሸፍናል። it i በርካታ የመጥፋት አደጋ ላይ ያሉ ዝርያዎችን ያቀፈ ሲሆን ከእነዚህም ውስጥ፡- የኢትዮጵያ ተኩላ፣ ዋሊያ የሜዳ ፍየል፣ ገላዳ ዝንጀሮ፣ ካራካል እና የመሳሰሉት።",
    g4:"ሰከላ አባይ የአለማችን ረጅሙ ወንዝ በሆነው አባይ (አባይ) ላይ አስደናቂ ጉዞ የጀመረ አስደናቂ የጉዞ ትርኢት ነው። ትርኢቱ አባይን (አባይን) ለ365 ቀናት ያለማቋረጥ ይከተላል። በሰከላ ከአባይ ምንጭ ጀምሮ ጀብዱ ይከፈታል። እሱ የበለፀገ ባህላዊ ቅርስ ፣ መልክዓ ምድሮች እና በአባይ ወንዝ ላይ ያሉ ሰዎች ነው። ከተረጋጋው ጅምር ጀምሮ እስከ ኃይለኛ ፍሰት የታችኛው ክፍል፣ እያንዳንዱ አፍታ ይያዛል።",
    g5:"ታና በደቡብ ምዕራብ የፓሲፊክ ውቅያኖስ ውስጥ በቫኑዋቱ ታፌ ግዛት ውስጥ የምትገኝ ደሴት ናት። ርዝመቱ 25 ማይል እና 12 ማይል ስፋት ያለው ሲሆን በድምሩ 212 ስኩዌር ማይል ነው።ታና የሚለው ስም በኳመራ ቋንቋ ጣና ከሚለው ቃል የተገኘ ሲሆን ትርጉሙም ምድር ማለት ነው። ጣና መነሻው እሳተ ገሞራ ሲሆን ሞቃታማ የአየር ንብረት ስላላት በቫኑዋቱ ውስጥ በጣም ለም ደሴት ያደርጋታል። ኮፕራ፣ ቡና እና ከብቶችን ለውጭ ገበያ ያመርታል። ደሴቱ በ1,084 ሜትር ከፍታ ያለው የቱኮስመራ ተራራ መኖሪያ ነው።",
    t1:"በዘመናዊቷ ኢትዮጵያ የምትገኘው በጥንቷ አክሱም ከተማ የሚገኘው የአክሱም ስልጣኔ በአስደናቂ ሀውልቶቹ በተለይም አሀዳዊ ሀውልቶች ይታወቃል።እነዚህ ሀውልቶች ከክርስቶስ ልደት በኋላ በ3ኛው እና በ4ኛው መቶ ክፍለ ዘመን የተፈጠሩ ልዩ የሰው ልጅ የፈጠራ ስራዎች ድንቅ ስራዎች ናቸው የተቀረፀው በዋናነት ጠንካራ የኒፊሊን ሳይኒት ብሎኮች፣ እነዚህ ሐውልቶች ከአክሱም በስተ ምዕራብ ከበርካታ ማይሎች ርቀት ላይ ከሚገኙ የድንጋይ ድንጋዮች እንደመጡ ይታመናል። ረጃጅሞቹ የንጉሣዊ ቤተሰብ አባላትን ያከብሩ ይሆናል፣ ትንሹ ግን በአካባቢው ልሂቃን የተሾሙ ናቸው።",
    t2:"አክሱም ጽዮን ማርያም ጽዮን በመባልም የምትታወቀው የኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተ ክርስቲያን በሰሜን ኢትዮጵያ በትግራይ ክልል የምትገኝ የተቀደሰ ቦታ ናት። ይህች ቤተ ክርስቲያን ክርስትና በሀገሪቱ ከገባችበት ጊዜ ጀምሮ በኢትዮጵያ ውስጥ ካሉት አንጋፋዎች አንዱ ነው ተብሎ ይታሰባል። አፄ ፋሲለደስ በ16ኛው መቶ ክፍለ ዘመን በአህመድ ኢብኑ ኢብራሂም አል-ጋዚ ከተደመሰሰ በኋላ አጼ ፋሲለደስ መልሰው የገነቡት ሲሆን አፄ ሀይለስላሴም አሁን ያለውን የቤተክርስቲያን መዋቅር በ1950ዎቹ ገነቡት።",
    t3:"አል ነጃሺ መስጂድ በትግራይ ነጋሽ ውስጥ ይገኛል። ከ615 ከክርስቶስ ልደት በኋላ የመጀመሪያዎቹ ሙስሊሞች በመካ የደረሰባቸውን ስደት ሸሽተው ወደ አቢሲኒያ በተሰደዱበት ከ615 ዓ.ም በኋላ የተመሰረተው በአፍሪካ የመጀመሪያው መስጂድ እንደሆነ ይታመናል።መስጂዱ የተሰየመው በነጃሺ ስም ሲሆን ለቀደምት ሙስሊሞች መጠጊያ ታሪካዊ ጠቀሜታ አለው። . እ.ኤ.አ. በ 2018 መስጂዱ ከቱርክ ትብብር እና ማስተባበሪያ ኤጀንሲ በተገኘ የገንዘብ ድጋፍ እድሳት ተደረገ ።",
    t4:"ደብረ ዳሞ በትግራይ ሰሜናዊ ክፍል በገለልተኛ ተራራ ላይ የሚገኝ ገዳም ነው። የተገነባው በስድስተኛው መቶ ክፍለ ዘመን ሲሆን ከአብዛኞቹ የኢትዮጵያ ገዳማት ጋር ሲነጻጸር ልዩ ነው። ደብረ ዳሞ ከገደል ላይ በሚወርድ ከተለጠፈ ሌዘር በተሰራ ገመድ ወደ ላይ መውጣት ብቻ ነው የሚጎበኘው ጎብኝዎች በወገባቸው አስረው ከዛ ገደል አናት ላይ ያለው መነኩሴ ይጎትታል። ለወንዶች እና ለወንዶች እንስሳት ብቻ ተደራሽ ነው.",
    t5:"አቡነ የሚማታ ጉህ በትግራይ ክልል ሀውዜን ወረዳ የሚገኝ አንድ አሀዳዊ ቤተ ክርስቲያን ነው። በ2,580 ሜትሮች (8,460 ጫማ) ከፍታ ላይ የምትገኘው ይህች ቤተ ክርስቲያን ፈታኝ ቢሆንም ጠቃሚ በሆነው አቀበት እና ታሪካዊ ጠቀሜታዋ ትታወቃለች። በገራልታ አካባቢ ባለው ረጅም የአሸዋ ድንጋይ ምሽግ ጎን የተቀረጸው ቤተ ክርስቲያኑ በ5ኛው መቶ ክፍለ ዘመን የጀመረች ሲሆን በኢትዮጵያ ክርስትናን በማስፋፋት ወሳኝ ሚና ከተጫወቱት ዘጠኙ ቅዱሳን መካከል አንዱ ለሆነው ለአቡነ ይምዓታ የተሰጠ ነው።"



  }
};

langButton.addEventListener('click', () => {
  currentLanguage = currentLanguage === 'en' ? 'amh' : 'en';

  descriptions.forEach(each => {
    const id = each.id;
    each.textContent = translations[currentLanguage][id];
  
  });
let contain='';

if(langButton.textContent==="Amh"){
  langButton.textContent="en";

}else if(langButton.textContent==="en"){
  langButton.textContent="Amh";
}

});